### ISSUE TITLE
cepa.univariate() possible bug.

### ISSUE THREAD

**Issue by lashmore** [jokergoo/CePa#1]
if (length(gene.in.node.in.mat) == 1) {
                  mat.node[i, ] = mat.gene[gene.in.node.in.mat,  ]
} else if (length(gene.in.node.in.mat > 1)) {   
                  ...
}

ELSE IF clause looks like a bug. Should it read the below instead?

else if (length(gene.in.node.in.mat) > 1) {   
                  ...
}

**Comment by jokergoo** [comment]
Yes, you are right. I have updated the package.

And thanks for reading the source code of this package. This package was written almost 10 years ago and I haven't looked into it for years. There might be a lot fo improper coding inside.
