### ISSUE TITLE
find.nlevelFun() and find.plevelFun()

### ISSUE THREAD

**Issue by lashmore** [jokergoo/CePa#2]
I'm debugging this R package, and I can't find these functions which are called by cepa.univariate().

nlevelFun = find.nlevelFun(nlevel)
plevelFun = find.plevelFun(plevel)

Please include some direction about these functions in the cepa.univariate() function, as it is unclear how important these lines are.

**Comment by jokergoo** [comment]
They are here:
https://github.com/jokergoo/CePa/blob/0c5f7535cfb88b5446b9b03cecb4b84345bedfb5/R/univariate_extension.R#L435-L468

They are used to find the corresponding function which calculates proper statistic for the node and for the pathway.

**Comment by lashmore** [comment]
Excellent - I must have missed them! Thank you!
